import { ProjectBlueprint } from "../project/types/project-blueprint";
import { Utils } from "../utils";
import { ValueKind } from "../project/types/values";

export const blankBlueprint: ProjectBlueprint = {
  format: 1,
  kind: "cdk/project-blueprint",
  extend: "cdk-base",
  id: "b8147ccc-d4a0-4865-b70c-e987bb1d0622",
  name: "Blank",
  description: "Blank blueprint with no constructs",
  icon: "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2U9IndoaXRlIiBhcmlhLWhpZGRlbj0idHJ1ZSI+PHBhdGggc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBkPSJNNyAyMWgxMGEyIDIgMCAwMDItMlY5LjQxNGExIDEgMCAwMC0uMjkzLS43MDdsLTUuNDE0LTUuNDE0QTEgMSAwIDAwMTIuNTg2IDNIN2EyIDIgMCAwMC0yIDJ2MTRhMiAyIDAgMDAyIDJ6Ij48L3BhdGg+PC9zdmc+",
  background: "#ec489a",
  favorites: [
    "aws-cdk-lib.Stack",
    "aws-cdk-lib.NestedStack",
    "aws-cdk-lib.aws_s3.Bucket",
  ],
  libs: {
    "@aws-cdk/aws-amplify-alpha": "2.x",
    "@aws-cdk/aws-apigatewayv2-alpha": "2.x",
    "@aws-cdk/aws-apigatewayv2-authorizers-alpha": "2.x",
    "@aws-cdk/aws-apigatewayv2-integrations-alpha": "2.x",
    "@aws-cdk/aws-apprunner-alpha": "2.x",
    "@aws-cdk/aws-appsync-alpha": "2.x",
    "@aws-cdk/aws-batch-alpha": "2.x",
    "@aws-cdk/aws-cloud9-alpha": "2.x",
    "@aws-cdk/aws-codestar-alpha": "2.x",
    "@aws-cdk/aws-cognito-identitypool-alpha": "2.x",
    "@aws-cdk/aws-gamelift-alpha": "2.x",
    "@aws-cdk/aws-glue-alpha": "2.x",
    "@aws-cdk/aws-iot-actions-alpha": "2.x",
    "@aws-cdk/aws-iot-alpha": "2.x",
    "@aws-cdk/aws-iotevents-actions-alpha": "2.x",
    "@aws-cdk/aws-iotevents-alpha": "2.x",
    "@aws-cdk/aws-ivs-alpha": "2.x",
    "@aws-cdk/aws-kinesisanalytics-flink-alpha": "2.x",
    "@aws-cdk/aws-kinesisfirehose-alpha": "2.x",
    "@aws-cdk/aws-kinesisfirehose-destinations-alpha": "2.x",
    "@aws-cdk/aws-lambda-go-alpha": "2.x",
    "@aws-cdk/aws-lambda-python-alpha": "2.x",
    "@aws-cdk/aws-msk-alpha": "2.x",
    "@aws-cdk/aws-neptune-alpha": "2.x",
    "@aws-cdk/aws-redshift-alpha": "2.x",
    "@aws-cdk/aws-route53resolver-alpha": "2.x",
    "@aws-cdk/aws-s3objectlambda-alpha": "2.x",
    "@aws-cdk/aws-sagemaker-alpha": "2.x",
    "@aws-cdk/aws-servicecatalogappregistry-alpha": "2.x",
    "@aws-cdk/aws-synthetics-alpha": "2.x",
    "@aws-cdk/cloud-assembly-schema": "2.x",
    "@aws-cdk/cx-api": "2.x",
    "@aws-cdk/integ-tests-alpha": "2.x",
    "@aws-cdk/region-info": "2.x",
  },
  root: {
    kind: ValueKind.Instance,
    valueId: Utils.generateId(),
    valueName: "App",
    valueType: {
      fqn: "aws-cdk-lib.App",
    },
    parameters: {},
    children: [
      {
        kind: ValueKind.Instance,
        valueId: Utils.generateId(),
        valueName: "MyStack",
        valueType: {
          fqn: "aws-cdk-lib.Stack",
        },
        children: [],
        parameters: {},
      },
    ],
  },
};
